export type StockImageAsset = {
  src: string;
  title: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  kind: "photo" | "illustration";
  route: string;
};

const stockBase = "/images/stock";

export const STOCK_IMAGES = {
  turbo: {
    src: `${stockBase}/ceoturbo-digital-visibility-system.webp`,
    title: "Connected digital visibility system",
    alt: "A hand selecting business, commerce, content, and growth tools around a connected digital globe",
    caption: "Search, paid reach, owned content, and conversion tools work better when the business controls the connections.",
    width: 1200,
    height: 630,
    kind: "photo",
    route: "/",
  },
  seoFoundation: {
    src: `${stockBase}/seo-services-foundation.webp`,
    title: "SEO services foundation",
    alt: "SEO services illustration representing the technical foundation of a search-ready website",
    caption: "The fixed website package combines crawlable structure, useful content, metadata, and indexing setup.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/seo-websites",
  },
  seoStructure: {
    src: `${stockBase}/technical-seo-structure.webp`,
    title: "Technical SEO structure",
    alt: "Blue technical SEO diagram showing keywords, internal linking, crawlability, reporting, and site structure",
    caption: "Technical SEO connects page structure, internal links, crawlability, relevance, and measurement.",
    width: 1200,
    height: 630,
    kind: "photo",
    route: "/seo-websites",
  },
  seoPerformance: {
    src: `${stockBase}/seo-performance-analysis.webp`,
    title: "SEO performance analysis",
    alt: "Magnifying glass examining a rising website performance chart",
    caption: "Measurement starts with a visible baseline and continues with real search data after launch.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/seo-websites",
  },
  metadata: {
    src: `${stockBase}/meta-description-optimization.webp`,
    title: "Page title and meta description planning",
    alt: "Keyboard key labeled meta description for webpage search-result copy",
    caption: "Each indexable page receives a distinct title and description aligned with its visible purpose.",
    width: 1200,
    height: 630,
    kind: "photo",
    route: "/seo-websites",
  },
  metadataCode: {
    src: `${stockBase}/website-metadata-code.webp`,
    title: "Website metadata in code",
    alt: "Close-up of webpage head and meta elements in source code",
    caption: "Metadata is implemented in the page source, then checked against canonicals, schema, and social previews.",
    width: 1200,
    height: 630,
    kind: "photo",
    route: "/seo-websites",
  },
  websiteDiscovery: {
    src: `${stockBase}/business-website-discovery.webp`,
    title: "Owned website destination",
    alt: "Web browser address bar with an HTTPS website address and cursor",
    caption: "A business-controlled domain gives searchers, ad visitors, and real-world prospects one dependable destination.",
    width: 1200,
    height: 630,
    kind: "photo",
    route: "/seo-websites",
  },
  seoGrowth: {
    src: `${stockBase}/seo-growth-measurement.webp`,
    title: "SEO growth measurement",
    alt: "SEO letters in front of a rising multicolor performance chart",
    caption: "Growth is evaluated over time; no single graphic, launch, or submission guarantees a ranking.",
    width: 1200,
    height: 630,
    kind: "photo",
    route: "/seo-websites",
  },
  searchConsole: {
    src: `${stockBase}/google-search-console-reporting.webp`,
    title: "Google Search Console reporting",
    alt: "Laptop displaying an illustrated Google Search Console performance report",
    caption: "Search Console helps confirm discovery, indexing, queries, clicks, impressions, and technical issues.",
    width: 860,
    height: 484,
    kind: "illustration",
    route: "/seo-websites",
  },
  metaPlatform: {
    src: `${stockBase}/meta-ads-platform.webp`,
    title: "Meta advertising platform",
    alt: "Blue Meta logo representing Facebook and Instagram advertising",
    caption: "Campaign access stays in client-controlled Meta business assets whenever platform permissions allow.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/meta-ads",
  },
  metaOptimization: {
    src: `${stockBase}/meta-campaign-optimization.webp`,
    title: "Campaign optimization system",
    alt: "Green gears and upward arrows representing ongoing Meta campaign optimization",
    caption: "Creative, delivery, response quality, cost per result, and budget pacing are reviewed together.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/meta-ads",
  },
  metaResults: {
    src: `${stockBase}/meta-campaign-results.webp`,
    title: "Recorded campaign results",
    alt: "Green results banner representing recorded advertising outcomes",
    caption: "Results are reported from supplied campaign screenshots with spend and cost per result—not projections.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/meta-ads",
  },
  shirtsDesigner: {
    src: `${stockBase}/custom-company-shirt-design.webp`,
    title: "Custom company shirt design",
    alt: "Illustrated online shirt designer showing a bright branded T-shirt",
    caption: "The shirt starts with a readable brand treatment that can survive real printing and normal viewing distance.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/shirts",
  },
  professionalShirt: {
    src: `${stockBase}/professional-company-shirt.webp`,
    title: "Professional company presentation",
    alt: "Illustrated clean dress shirt and tie representing a professional company appearance",
    caption: "A consistent team appearance makes the business easier to recognize before a customer sees a card or website.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/shirts",
  },
  businessCard: {
    src: `${stockBase}/custom-business-card-design.webp`,
    title: "Custom business card design",
    alt: "Business card illustration representing a clear branded contact handoff",
    caption: "The printed card carries the business name, contact path, and a destination the company controls.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/business-cards",
  },
  businessCardFollowUp: {
    src: `${stockBase}/business-card-follow-up.webp`,
    title: "Business card follow-up path",
    alt: "Business card illustration representing the next step after an in-person conversation",
    caption: "A QR code and readable fallback URL reduce friction without replacing the human introduction.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/business-cards",
  },
  honestReview: {
    src: `${stockBase}/honest-review-request.webp`,
    title: "Honest review request",
    alt: "Green checkmark badge representing a clear and policy-safe review request",
    caption: "The request asks every eligible customer for honest feedback without incentives, gating, or rating pressure.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/review-cards",
  },
  companyOperations: {
    src: `${stockBase}/company-operations-system.webp`,
    title: "Company operations behind the visibility system",
    alt: "Company building and gear illustration representing coordinated business operations",
    caption: "CEOTurbo coordinates the build, accounts, assets, measurement, and handoff around the real business.",
    width: 1200,
    height: 630,
    kind: "illustration",
    route: "/about",
  },
} satisfies Record<string, StockImageAsset>;

export const allStockImages = Object.values(STOCK_IMAGES);
